---
title: "Mutation Rate"
author: "Jcb Nunez"
date: "12/5/2020"
output: html_document
---

# Load Packages
```{r}
#############################
#############################

library(tidyverse)
library(magrittr)
library(reshape2)
library(vroom)
library(rcompanion)
library(patchwork)
library(plot3D)
library(viridis)
library(car)

```

# Load Data
```{r}
#############################
#############################

load("/Users/jcbnunez/Documents/GitHub/DEST_workspace/Endemism_New_Plot_JCBN/allSummarySet_endemism.bothCallers.Rdata")
```

#Plot Mutation Rates

```{r}

o2.ag.all %>%
  .[which(.$chr == "2R"),] %>%
  ggplot(aes(x=nPop, y=logit(freq), color = caller)) + 
  geom_line() + 
  #geom_smooth(method = "lm", size = 0.7, color = "grey") +
  facet_grid(~mt) + 
  theme_classic()


o2.ag.all %>%
  .[which(.$chr == "2R"),] %>%
  dcast(nPop+mt+chr~caller, value.var = "freq") -> mutation_dcast
mutation_dcast %>% ggplot(aes(x=PoolSNP, y=SNAPE)) + geom_point() + facet_wrap(~mt, scales = "free")
mutation_dcast$mt %>% unique() -> mut_types

output=data.frame(mut=mut_types)
for(i in 1:length(mut_types)){
  cor.test(mutation_dcast$PoolSNP[which(mutation_dcast$mt == mut_types[i])],
           mutation_dcast$SNAPE[which(mutation_dcast$mt == mut_types[i])], 
           na.rm = T) -> tmp
  output$cor[i] = tmp$estimate
  output$corU[i] = tmp$conf.int[2]
  output$corL[i] = tmp$conf.int[1]

}

output %>% ggplot(aes(x=mut, y=cor, ymin=corL, ymax = corU)) + geom_errorbar(width = 0.3) + geom_point() + geom_hline(yintercept = 0)


### LM
o2.ag.all %>%
  .[which(.$chr == "2R")] %>%
  dcast(nPop+mt+chr~caller, value.var = "freq") -> mutation_dcast

output_LM=data.frame(mut=mut_types)
for(i in 1:length(mut_types)){
  summary(
    lm(SNAPE~nPop, data=mutation_dcast[which(mutation_dcast$mt == mut_types[i]),])
    ) -> tmp1
 
  output_LM$beta_SNAPE[i]= tmp1$coefficients[2,1]
  output_LM$SE_SNAPE[i]= tmp1$coefficients[2,2]

  summary(
    lm(PoolSNP~nPop, data=mutation_dcast[which(mutation_dcast$mt == mut_types[i]),])
    ) -> tmp2
  
  output_LM$beta_PoolSNP[i]= tmp2$coefficients[2,1]
  output_LM$SE_PoolSNP[i]= tmp2$coefficients[2,2]
}

output_LM %>% melt(id="mut") %>% separate(variable, into = c("est","caller"), sep = "_") %>% dcast(mut+caller~est, value.var = "value") %>% ggplot(aes(color = caller, x=mut, y=beta, ymin=beta-SE*1.96, ymax = beta+SE*1.96)) + geom_errorbar(width = 0.3) + geom_point() + geom_hline(yintercept = 0)

output_LM %>% 
  melt(id="mut") %>% 
  separate(variable, into = c("est","caller"), sep = "_") %>% 
  dcast(mut+est~caller, value.var = "value") %>% 
  .[which(.$est == "beta"),] %>% 
  ggplot(aes(x = mut, ymin=PoolSNP, ymax=SNAPE)) + 
  geom_linerange(size = 1) + 
  geom_point(aes(y=PoolSNP), color = "blue", size = 3) + 
  geom_point(aes(y=SNAPE), color = "red", size = 3) + 
  geom_hline(yintercept = 0) +
  ylab("Beta SNAPE - Beta PoolSNP") +
  theme_bw()

```

